import { CaseStatus } from "@prisma/client";

export const DOCUMENT_CODES = {
  TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS",
  CONTRACT: "CONTRACT",
  INTAKE_FORM: "INTAKE_FORM",
  OUTTAKE_FORM: "OUTTAKE_FORM",
} as const;

export const CASE_TRANSITIONS: Record<CaseStatus, CaseStatus[]> = {
  NEW: [CaseStatus.AWAITING_REVIEW, CaseStatus.MATCHED, CaseStatus.CLOSED],
  AWAITING_REVIEW: [CaseStatus.MATCHED, CaseStatus.CLOSED],
  MATCHED: [
    CaseStatus.COUNSELLOR_PROPOSED,
    CaseStatus.AGREEMENT_PENDING,
    CaseStatus.READY_TO_SCHEDULE,
  ],
  COUNSELLOR_PROPOSED: [CaseStatus.COUNSELLOR_ACCEPTED, CaseStatus.MATCHED],
  COUNSELLOR_ACCEPTED: [CaseStatus.SLOT_PROPOSED, CaseStatus.AGREEMENT_PENDING],
  AGREEMENT_PENDING: [CaseStatus.READY_TO_SCHEDULE],
  READY_TO_SCHEDULE: [CaseStatus.SLOT_PROPOSED, CaseStatus.SCHEDULED],
  SLOT_PROPOSED: [CaseStatus.SLOT_CONFIRMED, CaseStatus.READY_TO_SCHEDULE, CaseStatus.COUNSELLOR_ACCEPTED],
  SLOT_CONFIRMED: [CaseStatus.SCHEDULED, CaseStatus.READY_TO_SCHEDULE, CaseStatus.AGREEMENT_PENDING],
  SCHEDULED: [CaseStatus.IN_SESSION],
  IN_SESSION: [CaseStatus.COMPLETED],
  COMPLETED: [CaseStatus.CLOSED],
  CLOSED: [],
};

export const REQUIRED_DOCUMENTS_TO_ENTER: Partial<Record<CaseStatus, string[]>> = {
  [CaseStatus.READY_TO_SCHEDULE]: [DOCUMENT_CODES.TERMS_AND_CONDITIONS],
  [CaseStatus.IN_SESSION]: [DOCUMENT_CODES.TERMS_AND_CONDITIONS],
  [CaseStatus.CLOSED]: [DOCUMENT_CODES.OUTTAKE_FORM],
};
